const top1 = document.getElementsByClassName('top1')[0]
const topRight1 = document.getElementsByClassName('top-right1')[0]
const topLeft1 = document.getElementsByClassName('top-left1')[0]
const middle1 = document.getElementsByClassName('middle1')[0]
const bottomRight1 = document.getElementsByClassName('bottom-right1')[0]
const bottomLeft1 = document.getElementsByClassName('bottom-left1')[0]
const bottom1 = document.getElementsByClassName('bottom1')[0]

const top2 = document.getElementsByClassName('top2')[0]
const topRight2 = document.getElementsByClassName('top-right2')[0]
const topLeft2 = document.getElementsByClassName('top-left2')[0]
const middle2 = document.getElementsByClassName('middle1')[0]
const bottomRight2 = document.getElementsByClassName('bottom-right2')[0]
const bottomLeft2 = document.getElementsByClassName('bottom-left2')[0]
const bottom2 = document.getElementsByClassName('bottom2')[0]

const top3 = document.getElementsByClassName('top3')[0]
const topRight3 = document.getElementsByClassName('top-right3')[0]
const topLeft3 = document.getElementsByClassName('top-left3')[0]
const middle3 = document.getElementsByClassName('middle3')[0]
const bottomRight3 = document.getElementsByClassName('bottom-right3')[0]
const bottomLeft3 = document.getElementsByClassName('bottom-left3')[0]
const bottom3 = document.getElementsByClassName('bottom3')[0]

const top4 = document.getElementsByClassName('top4')[0]
const topRight4 = document.getElementsByClassName('top-right4')[0]
const topLeft4 = document.getElementsByClassName('top-left4')[0]
const middle4 = document.getElementsByClassName('middle4')[0]
const bottomRight4 = document.getElementsByClassName('bottom-right4')[0]
const bottomLeft4 = document.getElementsByClassName('bottom-left4')[0]
const bottom4 = document.getElementsByClassName('bottom4')[0]

